### ISSUE TITLE
Put the front of the benny in the character sheet

### ISSUE THREAD

**Issue by javierriveracastro** [SalieriC/SWADE-Benny-Configurator#1]
The Official Character sheet is showing the default benny image, not the one that you choose in settings. That's inconsistent and can confuse users.

**Comment by SalieriC** [comment]
Make a pull request. :-P

**Comment by javierriveracastro** [comment]
I don't know coding. It is scaring stuff, can't you do it for me?

**Comment by javierriveracastro** [comment]
XDD. That was low... you sure are developer material.

**Comment by SalieriC** [comment]
Done... Mostly by yourself. :D
